name: linter

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.5'
          extensions: gd, imagick

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          composer-options: '--no-scripts'

      - name: Install Node Dependencies
        run: npm install

      - name: Run Pint
        run: composer lint

      - name: Run Rector
        run: composer refactor:check

      - name: Format Frontend
        run: npm run format:check

      - name: Lint Frontend
        run: npm run lint
